steps:

# Build Images
- id: Building image
  name: gcr.io/cloud-builders/docker
  args: ['build','-t', 'gcr.io/$PROJECT_ID/init:$SHORT_SHA', '-f', 'Dockerfile', '.']

# Push Images
- id: Pushing Image
  name: gcr.io/cloud-builders/docker
  args: ['push','gcr.io/$PROJECT_ID/init:$SHORT_SHA']